networks:
  local:

services:
  deer_postgres:
    image: postgres:14
    container_name: deer_postgres
    ports:
      - 3214:5432
    environment:
      POSTGRES_PASSWORD: 123456
    networks:
      - local

  deer_adminer:
    image: adminer:latest
    container_name: deer_adminer
    ports:
      - 9999:8080
    environment:
      ADMINER_DEFAULT_SERVER: deer_postgres
      ADMINER_DEFAULT_DRIVER: pgsql
      ADMINER_DEFAULT_DB: postgres
      ADMINER_DEFAULT_USERNAME: postgres
      ADMINER_DEFAULT_PASSWORD: 123456
    networks:
      - local